# Site settings
title: Matthew Toledo
email: mtoledo@albany.edu
description: Matt is an INF student from New York.
url: http://matthewtoledo.github.io
github_username: matthewtoledo

# Build settings
markdown: kramdown
permalink: pretty
